"""cria tabelas de usuarios e papeis

Revision ID: da11b06cc2e6
Revises: 
Create Date: 2021-01-15 19:43:07.069856

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da11b06cc2e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    role_table = op.create_table(
        'role',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    user_table = op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )

    roles_users_table = op.create_table(
        'roles_users',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )

    op.bulk_insert(
        role_table,
        [
            {'id': 0, 'name': 'admin', 'description': 'System admin'},
        ]
    )

    op.bulk_insert(
        user_table,
        [
            {'id': 0, 'first_name': 'Admin', 'email': 'admin', 'password': 'admin', 'active': True},
        ]
    )

    op.bulk_insert(
        roles_users_table,
        [
            {'user_id': 0, 'role_id': 0},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
